name: sgl
description: SGL implementation on Dart. SGL is originally written in python and is maintained by Evernym.
version: 0.0.1
homepage: https://github.com/ghabxph/dart_sgl

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  test: ^1.15.7
  pedantic: ^1.9.0
